parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: test
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 40883bff372c0554b1017107629556b4e6
    database_path: null
