Categories:
    type: entity
    table: categories
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 200
            fixed: false
            nullable: false
        description:
            type: text
            nullable: false
        slug:
            type: string
            length: 120
            fixed: false
            nullable: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    lifecycleCallbacks: {  }
