Comments:
    type: entity
    table: comments
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        email:
            type: string
            length: 200
            fixed: false
            nullable: true
        content:
            type: text
            nullable: true
        dateCreated:
            type: datetime
            nullable: true
            column: date_created
    lifecycleCallbacks: {  }
