Links:
    type: entity
    table: links
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 250
            fixed: false
            nullable: false
        link:
            type: string
            length: 250
            fixed: false
            nullable: false
        description:
            type: text
            nullable: false
        dateCreated:
            type: datetime
            nullable: true
            column: date_created
    lifecycleCallbacks: {  }
