Pages:
    type: entity
    table: pages
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 250
            fixed: false
            nullable: false
        resume:
            type: text
            nullable: false
        content:
            type: text
            nullable: false
        tag:
            type: string
            length: 300
            fixed: false
            nullable: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateUpdated:
            type: datetime
            nullable: false
            column: date_updated
    lifecycleCallbacks: {  }
