Tags:
    type: entity
    table: tags
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        categoryId:
            type: integer
            unsigned: false
            nullable: true
            column: category_id
        tag:
            type: string
            length: 300
            fixed: false
            nullable: true
        dateCreated:
            type: datetime
            nullable: true
            column: date_created
    lifecycleCallbacks: {  }
