articles:
    pattern:  /
    defaults: { _controller: "SiteAdminBundle:Articles:index" }

articles_show:
    pattern:  /show/{id}
    defaults: { _controller: "SiteAdminBundle:Articles:show" }

articles_new:
    pattern:  /new
    defaults: { _controller: "SiteAdminBundle:Articles:new" }

articles_create:
    pattern:  /create
    defaults: { _controller: "SiteAdminBundle:Articles:create" }
    requirements: { _method: post }

articles_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "SiteAdminBundle:Articles:edit" }

articles_update:
    pattern:  /update/{id}
    defaults: { _controller: "SiteAdminBundle:Articles:update" }
    requirements: { _method: post }

articles_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "SiteAdminBundle:Articles:delete" }
    requirements: { _method: post }
