search_query:
    pattern:  /search
    defaults: { _controller: "SiteAdminBundle:Slot:search" }
    requirements: { _method: post }

search_query_ajax:
    pattern:  /searchajax
    defaults: { _controller: "SiteAdminBundle:Slot:searchajax" }
    options:
        expose: true

displaying:
    pattern:  /displaying/{page}
    defaults: { _controller: "SiteAdminBundle:Slot:displaying" , page: 5}

other:
    pattern:  /notfound
    defaults: { _controller: "SiteAdminBundle:Default:index" }

    

