<?php

namespace Site\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SidebarController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Site\AdminBundle\Controller\SidebarController();
        return $instance;
    }
}
