parameters:
    email_administrateur: zuzu38080@gmail.com
    limit_per_page: 6
    sidebar_entities:
       Articles:
            field: 'title'
            orderBy: 'title'
            orderWay: 'Desc'
            limit: 5
       Categories:
            field: 'title'
            orderBy: 'title'
            orderWay: 'Desc'
            limit: 5
       Medias:
            field: 'picture'
            orderBy: 'dateCreated'
            orderWay: 'Desc'
            limit: 5
     
    SearchQuery: >
            SELECT a FROM SiteAdminBundle:Articles a
            LEFT JOIN  a.category c
            WHERE a.title = :title
            OR  c.title = :titleb
            ORDER BY a.title ASC
     
    SearchAjaxQuery: 
            - SELECT a.title FROM SiteAdminBundle:Articles a WHERE a.title LIKE  ?1  ORDER BY a.title ASC
            - SELECT a.title FROM SiteAdminBundle:Categories a WHERE a.title LIKE  ?1  ORDER BY a.title ASC
            - SELECT a.legend AS title FROM SiteAdminBundle:Medias a WHERE a.legend LIKE  ?1  ORDER BY a.legend ASC
      
twig:
    globals:
        nom_site: Julovik
        slogan:  CMF for EveryBody
        topmenu:
          - {label: 'Home', routing: 'home' }
          - {label: 'Articles', routing: 'articles'}
          - {label: 'Categories', routing: 'categories' }
#          - {label: 'Liens', routing: 'links', subrouting : [ {label: 'Categories', routing: 'categories' },{label: 'Liens', routing: 'links' } {label: 'Medias', routing: 'medias' }]  }
          - {label: 'Liens', routing: 'links'  }
          - {label: 'Medias', routing: 'medias'  }
          - {label: 'Commentaires', routing: 'comments'  }
          - {label: 'Tags', routing: 'tags' }
          - {label: 'Autres', routing: 'other', subrouting : [{label: 'Pages', routing: 'pages'  }, {label: 'Administrateurs', routing: 'administrateurs'  }, {label: 'Référencement', routing: 'referencement'  }]  }
        fastactions:
          - {'label': 'Nouvel Article', routing: 'articles_new' }
          - {'label': 'Nouvel Catégorie', routing: 'categories_new' }
          - {'label': 'Nouveau Link', routing: 'links_new' }
          - {'label': 'Nouvelle Page', routing: 'pages_new' }
          - {'label': 'Nouveau Media', routing: 'medias_new' }
        sidebar:
          - {'label': 'Nouvel Article', routing: 'articles_new' }
          - {'label': 'Nouvel Catégorie', routing: 'categories_new' }
          - {'label': 'Nouveau Link', routing: 'links_new' }
        advices:
          - Conseil ici numéro 1
          - Conseil ici numéro 2
          - Conseil ici numéro 3
          - Conseil ici numéro 4
          - Conseil ici numéro 5
          - Conseil ici numéro 6
