
#Homepage
home:
    pattern:  /
    defaults: { _controller: "SiteAdminBundle:Articles:index" }

site_admin_homepage:
    pattern:  /demo
    defaults: { _controller: SiteAdminBundle:Default:index }

#Security Routing
login:
  pattern: /login
  defaults: { _controller: SiteAdminBundle:Security:login }

login_check:
  pattern: /login_check
 
logout:
  pattern: /logout  


#All Modules
articles:
    resource: "@SiteAdminBundle/Resources/config/routing/articles.yml"
    prefix:   /articles
    
categories:
    resource: "@SiteAdminBundle/Resources/config/routing/categories.yml"
    prefix:   /categories
    
comments:
    resource: "@SiteAdminBundle/Resources/config/routing/comments.yml"
    prefix:   /comments
    
links:
    resource: "@SiteAdminBundle/Resources/config/routing/links.yml"
    prefix:   /links
    
medias:
    resource: "@SiteAdminBundle/Resources/config/routing/medias.yml"
    prefix:   /medias
    
tags:
    resource: "@SiteAdminBundle/Resources/config/routing/tags.yml"
    prefix:   /tags
    
users:
    resource: "@SiteAdminBundle/Resources/config/routing/users.yml"
    prefix:   /users
    
divers:
    resource: "@SiteAdminBundle/Resources/config/routing/divers.yml"
    prefix:   /
    
administrateurs:
    resource: "@SiteAdminBundle/Resources/config/routing/administrateurs.yml"
    prefix:   /
    
pages:
    resource: "@SiteAdminBundle/Resources/config/routing/pages.yml"
    prefix:   /pages
    
parametres:
    resource: "@SiteAdminBundle/Resources/config/routing/parametres.yml"
    prefix:   /parametres
    
referencement:
    resource: "@SiteAdminBundle/Resources/config/routing/referencement.yml"
    prefix:   /referencement
    
    
notifications:
    resource: "@SiteAdminBundle/Resources/config/routing/notifications.yml"
    prefix:   /notifications
    
#FOS Routing
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

