parameters:
#    site_admin.example.class: Site\AdminBundle\Example

services:
#    site_admin.example:
#        class: %site_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
