<?php

namespace Proxies\__CG__\Site\AdminBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Users extends \Site\AdminBundle\Entity\Users implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCityId($cityId)
    {
        $this->__load();
        return parent::setCityId($cityId);
    }

    public function getCityId()
    {
        $this->__load();
        return parent::getCityId();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setTel($tel)
    {
        $this->__load();
        return parent::setTel($tel);
    }

    public function getTel()
    {
        $this->__load();
        return parent::getTel();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setDob($dob)
    {
        $this->__load();
        return parent::setDob($dob);
    }

    public function getDob()
    {
        $this->__load();
        return parent::getDob();
    }

    public function setOptin($optin)
    {
        $this->__load();
        return parent::setOptin($optin);
    }

    public function getOptin()
    {
        $this->__load();
        return parent::getOptin();
    }

    public function setIp($ip)
    {
        $this->__load();
        return parent::setIp($ip);
    }

    public function getIp()
    {
        $this->__load();
        return parent::getIp();
    }

    public function setSalt($salt)
    {
        $this->__load();
        return parent::setSalt($salt);
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function setToken($token)
    {
        $this->__load();
        return parent::setToken($token);
    }

    public function getToken()
    {
        $this->__load();
        return parent::getToken();
    }

    public function setDon($don)
    {
        $this->__load();
        return parent::setDon($don);
    }

    public function getDon()
    {
        $this->__load();
        return parent::getDon();
    }

    public function setQ1($q1)
    {
        $this->__load();
        return parent::setQ1($q1);
    }

    public function setPicture($picture)
    {
        $this->__load();
        return parent::setPicture($picture);
    }

    public function getPicture()
    {
        $this->__load();
        return parent::getPicture();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setDateAuth($dateAuth)
    {
        $this->__load();
        return parent::setDateAuth($dateAuth);
    }

    public function getDateAuth()
    {
        $this->__load();
        return parent::getDateAuth();
    }

    public function setCounterUpdated($counterUpdated)
    {
        $this->__load();
        return parent::setCounterUpdated($counterUpdated);
    }

    public function getCounterUpdated()
    {
        $this->__load();
        return parent::getCounterUpdated();
    }

    public function setCounterFailed($counterFailed)
    {
        $this->__load();
        return parent::setCounterFailed($counterFailed);
    }

    public function getCounterFailed()
    {
        $this->__load();
        return parent::getCounterFailed();
    }

    public function setEnabled($enabled)
    {
        $this->__load();
        return parent::setEnabled($enabled);
    }

    public function getEnabled()
    {
        $this->__load();
        return parent::getEnabled();
    }

    public function setAccountnonlocked($accountnonlocked)
    {
        $this->__load();
        return parent::setAccountnonlocked($accountnonlocked);
    }

    public function getAccountnonlocked()
    {
        $this->__load();
        return parent::getAccountnonlocked();
    }

    public function setAccountnonexpired($accountnonexpired)
    {
        $this->__load();
        return parent::setAccountnonexpired($accountnonexpired);
    }

    public function getAccountnonexpired()
    {
        $this->__load();
        return parent::getAccountnonexpired();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setFid($fid)
    {
        $this->__load();
        return parent::setFid($fid);
    }

    public function getFid()
    {
        $this->__load();
        return parent::getFid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'cityId', 'gender', 'firstname', 'lastname', 'description', 'email', 'tel', 'password', 'dob', 'optin', 'ip', 'salt', 'token', 'don', 'picture', 'updatedAt', 'createdAt', 'dateAuth', 'counterUpdated', 'counterFailed', 'enabled', 'accountnonlocked', 'accountnonexpired', 'slug', 'fid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}